// gen-fielddocs 读取 internal/manifest/manifest.go 的字段注释，生成
// internal/manifest/fielddocs.go。构建产物里没有源码，运行时的 schema 子命令
// 直接读生成结果，因此改动 manifest 字段后必须重新生成。
//
// 用法：
//
//	go generate ./internal/manifest
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/zc310/ofd/internal/manifest/fielddocs"
)

func main() {
	root, err := repoRoot()
	if err != nil {
		fail(err)
	}
	source := filepath.Join(root, "internal", "manifest", "manifest.go")
	target := filepath.Join(root, "internal", "manifest", "fielddocs.go")
	schema, err := fielddocs.Extract(source)
	if err != nil {
		fail(err)
	}
	generated, err := render(schema)
	if err != nil {
		fail(err)
	}
	current, err := os.ReadFile(target)
	if err == nil && bytes.Equal(current, generated) {
		fmt.Printf("fielddocs.go 已是最新，共 %d 个结构体、%d 个字段\n", len(schema.Types), schema.FieldCount())
		return
	}
	if err := os.WriteFile(target, generated, 0o644); err != nil {
		fail(fmt.Errorf("写入 %s 失败: %w", target, err))
	}
	fmt.Printf("已生成 %s，共 %d 个结构体、%d 个字段\n", target, len(schema.Types), schema.FieldCount())
}

// render 生成 fielddocs.go 源码。
func render(schema fielddocs.Schema) ([]byte, error) {
	var out bytes.Buffer
	out.WriteString("// Code generated by gen-fielddocs from manifest.go; DO NOT EDIT.\n\n")
	out.WriteString("package manifest\n\n")
	out.WriteString("// FieldDoc 是单个 manifest 字段的参考信息。\n")
	out.WriteString("type FieldDoc struct {\n")
	out.WriteString("\t// Name 是相对所属结构体的键名，也是 manifest 里的字段名。\n")
	out.WriteString("\tName string\n")
	out.WriteString("\t// Type 是该字段的 Go 类型，数组和指针保留书写形式。\n")
	out.WriteString("\tType string\n")
	out.WriteString("\t// Doc 是去掉字段名前缀后的字段说明。\n")
	out.WriteString("\tDoc string\n")
	out.WriteString("\t// Optional 表示该字段的 json tag 带 omitempty，未设置时零值即不输出。\n")
	out.WriteString("\tOptional bool\n")
	out.WriteString("}\n\n")
	out.WriteString("// TypeDoc 是 manifest 里一个结构体的字段说明。\n")
	out.WriteString("type TypeDoc struct {\n")
	out.WriteString("\t// Name 是 Go 结构体名。\n")
	out.WriteString("\tName string\n")
	out.WriteString("\t// Path 是从 manifest 根首次到达该结构体的路径，根结构体为空串。\n")
	out.WriteString("\tPath string\n")
	out.WriteString("\t// Doc 是结构体自身的说明。\n")
	out.WriteString("\tDoc string\n")
	out.WriteString("\t// Fields 是该结构体的直接字段。\n")
	out.WriteString("\tFields []FieldDoc\n")
	out.WriteString("}\n\n")
	out.WriteString("// SchemaDocs 是 manifest 的结构体说明集合，由 internal/manifest/fielddocs 从\n")
	out.WriteString("// manifest.go 的文档注释提取，供 ofd-creator schema 输出字段参考文档。改动\n")
	out.WriteString("// manifest 字段后执行 go generate ./internal/manifest 更新。\n")
	out.WriteString("// 每个结构体只展开一次，Path 记录首次到达它的示例路径。\n")
	out.WriteString("var SchemaDocs = []TypeDoc{\n")
	for _, typed := range schema.Types {
		fmt.Fprintf(&out, "\t{Name: %s, Path: %s, Doc: %s, Fields: []FieldDoc{\n",
			quote(typed.Name), quote(typed.Path), quote(typed.Doc))
		for _, field := range typed.Fields {
			fmt.Fprintf(&out, "\t\t{Name: %s, Type: %s, Doc: %s, Optional: %t},\n",
				quote(field.Name), quote(field.Type), quote(field.Doc), field.Optional)
		}
		out.WriteString("\t}},\n")
	}
	out.WriteString("}\n")
	return format.Source(out.Bytes())
}

func quote(value string) string {
	return fmt.Sprintf("%q", strings.TrimSpace(value))
}

// repoRoot 定位仓库根目录：go generate 的工作目录是包目录，向上找 go.mod。
func repoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("获取工作目录失败: %w", err)
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", os.ErrNotExist
		}
		dir = parent
	}
}

func fail(err error) {
	fmt.Fprintln(os.Stderr, "gen-fielddocs:", err)
	os.Exit(1)
}
